<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetBasePath>App_Plugins/CoreSystemII</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>CoreSystemII</PackageId>
    <Product>CoreSystemII</Product>
    <Title>CoreSystemII</Title>
    <Description>...</Description>
    <PackageTags>umbraco plugin package</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="HttpClientWrapper\**" />
    <Content Remove="HttpClientWrapper\**" />
    <EmbeddedResource Remove="HttpClientWrapper\**" />
    <None Remove="HttpClientWrapper\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Config\MapperConfig.cs" />
    <Compile Remove="Config\pmConfiguration.cs" />
    <Compile Remove="Controllers\AccountController.cs" />
    <Compile Remove="Controllers\AzureAccountController.cs" />
    <Compile Remove="Controllers\EditSectionPlanogramApiController.cs" />
    <Compile Remove="Controllers\LogoutController.cs" />
    <Compile Remove="Helpers\ControllerExtensions.cs" />
    <Compile Remove="Helpers\DictionaryExensions.cs" />
    <Compile Remove="Helpers\LogHelper.cs" />
    <Compile Remove="Helpers\MenuExtensions.cs" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.Graph" Version="5.83.0" />
    <PackageReference Include="Microsoft.identity.Web" Version="3.2.0" />
    <PackageReference Include="Microsoft.identity.Web.UI" Version="3.2.0" />
    <PackageReference Include="RazorEngine.NetCore" Version="3.1.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="7.0.2" />
    <PackageReference Include="Umbraco.Cms.Core" Version="15.0.0" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="15.0.0" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="15.0.0" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\PM-Application\PMApplication.csproj" />
    <ProjectReference Include="..\PM-Infrastructure\PMInfrastructure.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Config\" />
  </ItemGroup>
</Project>
